class MEET_PEOPLE_FILTER():
    FRIENDSHIP = "FRIENDSHIP"
    DATING = "DATING"
    VIEWED = "VIEWED"
    FAVORITES = "FAVORITES"
    MUTUALITY_USERS = "MUTUALITY_USERS"
    BEACON_USERS = "BEACON_USERS"
