class RELATIONSHIP_STATUS():

	SINGLE = "SINGLE"
	MARRIED = "MARRIED"
	COMPLICATED = "IT'S COMPLICATED"
	RELATIONSHIP = "IN A RELATIONSHIP"
	ENGAGED = "ENGAGED"
	DOMESTIC = "IN A DOMESTIC PARTNERSHIP"

	ENUM = (
			(SINGLE,"Single"),
			(MARRIED,"Married"),
			(COMPLICATED,"It's complicated"),
			(RELATIONSHIP,"In a relationship"),
			(ENGAGED,"Engaged"),
			(DOMESTIC,"Domestic"),
			)

