from getFriendList import GetFriendList
from getMutualFriendList import GetMutualFriendList
from getMatches import GetNewMatch,GetNewMatchIncludingPerson
from getMessages import GetRecentMessages, GetMessageThreadWithOther
from sendMessage import SendMessageToOtherProfile
from updateFriendList import UpdateFriendList
